config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :estimates do
    member do
      get :matchings
      post :matchings, to: "matchings#create"
    end
  end
  resources :partners
  resources :matchings, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :tel, presence: true, length: { maximum: 255 }
  validates :content, length: { maximum: 2000 }
  validates :status, presence: true, length: { maximum: 255 }
  has_many :matchings
  has_many :matched_partner, through: :matchings, source: :partner
  
  def matching(partner_id)
    self.matchings.find_or_create_by(partner_id: partner.id)
  end
  
  def matched?(partner)
    self.matched_partner.include?(partner)
  end
  
end

app/models/matching.rb
class Matching < ApplicationRecord
  belongs_to :partner
  belongs_to :estimate
end

app/models/partner.rb
class Partner < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :matchings
  has_many :matched_estimate, through: :matchings, source: :estimate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  include Pagy::Backend
  
  private

  def require_partner_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def require_admin_logged_in
    unless current_partner.admin?
      redirect_to current_partner
    end
  end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :require_partner_logged_in
  before_action :require_admin_logged_in

  def index
    @pagy, @estimates = pagy(Estimate.order(id: :desc), items: 10)
  end

  def show
    @estimate = Estimate.find(params[:id])
  end

  def new
    @estimate = Estimate.new
  end

  def create
    @estimate = Estimate.new(estimate_params)
    @estimate.status = "未面談"

    if @estimate.save
      flash[:success] = '見積依頼者を登録しました。'
      redirect_to @estimate
    else
      flash.now[:danger] = '見積依頼者の登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @estimate = Estimate.find(params[:id])
  end
  
  def update
    @estimate = Estimate.find(params[:id])
    
    if @estimate.status == "未面談"
      @estimate.status = "面談済み"
    end

    if @estimate.update(estimate_params)
      flash[:success] = "見積依頼者 は正常に更新されました"
      redirect_to @estimate
    else
      flash.now[:danger] = "見積依頼者 は更新されませんでした"
      render :edit
    end
  end
  
  def matchings
    @partners = Partner.all
    @estimate = Estimate.find(params[:id])
  end
  
  private

  def estimate_params
    params.require(:estimate).permit(:name, :address, :tel, :content, :status)
  end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController
  def create
    estimate = Estimate.find(params[:estimate_id])
    partner = Partner.find(params[:partner_id])
    matching = estimate.matchings.build(partner_id: partner.id)
    estimate.status = "アポイント済み"
    matching.save
    estimate.save
    flash[:success] = 'マッチングしました。'
    redirect_to partner
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :require_partner_logged_in, only: [:index, :show]
  
  def show
    if current_partner == Partner.find(params[:id]) or current_partner.admin == true
      @partner = Partner.find(params[:id])
      @estimates_list = @partner.matched_estimate.all
      @pagy, @estimates = pagy(@estimates_list.order(id: :desc), items: 10)
    else
      redirect_to current_partner
    end
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      flash[:success] = 'パートナー企業を登録しました。'
      redirect_to @partner
    else
      flash.now[:danger] = 'パートナー企業の登録に失敗しました。'
      render :new
    end
  end

  private

  def partner_params
    params.require(:partner).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to current_partner
    end
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @partner
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:partner_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_path
  end
  
  private

  def login(email, password)
    @partner = Partner.find_by(email: email)
    if @partner && @partner.authenticate(password)
      # ログイン成功
      session[:partner_id] = @partner.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_partner
    @current_partner ||= Partner.find_by(id: session[:partner_id])
  end

  def logged_in?
    !!current_partner
  end
end

app/views/estimates/_estimates.html.erb
<% if estimates.any? %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <th>登録日時</th>
      <th>氏名</th>
      <th>ステータス</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>面談内容</th>
    </thead>
    <% estimates.each do |estimate| %>
      <tr>
        <td><%= estimate.created_at.to_s(:datetime_jp) %></td>
        <td><%= link_to estimate.name, estimate_path(estimate.id) %></td>
        <td><%= estimate.status %></td>
        <td><%= estimate.address %></td>
        <td><%= estimate.tel %></td>
        <td><%= estimate.content %></td>
      </tr>
    <% end %>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

<div class="text-center">
  <p><%= link_to '見積依頼者登録', new_estimate_path %></p>
</div>

app/views/estimates/_partners.html.erb
<div class="container">
  <div class="row justify-content-sm-center">
    <div class="col-sm-auto"><a href="<%= estimate_path(estimate) %>"><%= estimate.name %></a></div>
    <div class="col-sm-auto">様へのマッチング候補</div>
  </div>
</div>

<div class="container">
  <% partners.each do |partner| %>
    <div class="row mt-1 justify-content-sm-center">
      <div class="col-1"><%= partner.name %></div>
      <div class="col-1">
        <%= render "matchings/matching_button", partner: partner, estimate: estimate %>
      </div>
    </div>
  <% end %>
</div>

app/views/estimates/create.html.erb
<h1>Estimates#create</h1>
<p>Find me in app/views/estimates/create.html.erb</p>

app/views/estimates/edit.html.erb
<%= form_with(model: @estimate) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <table class="table center-block">
    <tr>
      <th style="width: 30%"><%= f.label :name, "氏名" %></th>
      <td style="width: 70%"><%= f.text_field :name, value: @estimate.name, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :address, "住所" %></th>
      <td><%= f.text_field :address, value: @estimate.address, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :tel, "電話番号" %></th>
      <td><%= f.text_field :tel, value: @estimate.tel, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :content, "面談内容" %></th>
      <td><%= f.text_field :content, value: @estimate.content, class: 'form-control' %></td>
    </tr>
  </table>

  <div class="row justify-content-sm-center">
    <div class="col-sm-auto">
      <%= link_to "戻る", estimate_path(@estimate.id), class: "btn btn-secondary" %>
    </div>
    <div class="col-sm-auto">
      <%= f.submit '保存', class: "btn btn-primary" %>
    </div>
  </div>  

<% end %>

app/views/estimates/index.html.erb
<%= render 'estimates', estimates: @estimates %>

app/views/estimates/matchings.html.erb
<%= render 'partners', partners: @partners, estimate: @estimate  %>

app/views/estimates/new.html.erb
<div class="text-center">
  <h1>見積依頼者登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @estimate) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, '氏名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :address, '住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :tel, '電話番号' %>
        <%= f.text_field :tel, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/estimates/show.html.erb
<table class="table">
  <tr>
    <th style="width: 30%">氏名</th>
    <td style="width: 70%"><%= @estimate.name %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @estimate.address %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= @estimate.tel %></td>
  </tr>
  <tr>
    <th>面談内容</th>
    <td><%= @estimate.content %></td>
  </tr>
</table>

<div class="row justify-content-sm-center">
  <div class="col-sm-auto">
    <%= link_to "戻る", estimates_url, class: "btn btn-secondary" %>
  </div>
  <div class="col-sm-auto">
    <%= link_to "編集", edit_estimate_path(@estimate.id), class: "btn btn-primary" %>
  </div>
  <div class="col-sm-auto">
    <%= link_to "アポ調整", matchings_estimate_path(@estimate.id), class: "btn btn-success" %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">CRM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_partner.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/matchings/_matching_button.html.erb
<% if estimate.matched?(partner) %>
  <p>選択済み</p>
<% else %>
  <%= form_with(model: estimate.matchings.build) do |f| %>
    <%= hidden_field_tag :partner_id, partner.id %>
    <%= hidden_field_tag :estimate_id, estimate.id %>
    <%= f.submit '選択', class: 'btn btn-primary btn-block' %>
  <% end %>
<% end %>

app/views/partners/_estimates.html.erb
<div class="container">
  <div class="row justify-content-sm-left">
    <div class="col-sm-auto"><b><%= partner.name %></b></div>
    <div class="col-sm-auto">へマッチング済み見積依頼者一覧</div>
  </div>
</div>

<% if estimates.any? %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <th>登録日時</th>
      <th>氏名</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>面談内容</th>
    </thead>
    <% estimates.each do |estimate| %>
      <tr>
        <td><%= estimate.created_at.to_s(:datetime_jp) %></td>
        <td><%= estimate.name %></td>
        <td><%= estimate.address %></td>
        <td><%= estimate.tel %></td>
        <td><%= estimate.content %></td>
      </tr>
    <% end %>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

<% if current_partner.admin? %>
  <%= link_to "見積一覧", estimates_url, class: "btn btn-primary" %>
<% end %>

app/views/partners/create.html.erb
<h1>Partners#create</h1>
<p>Find me in app/views/partners/create.html.erb</p>

app/views/partners/new.html.erb
<div class="text-center">
  <h1>パートナー企業登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @partner) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, '企業名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/partners/show.html.erb
<%= render 'estimates', estimates: @estimates, partner: @partner %>